### ISSUE TITLE
Variable assignment

### ISSUE THREAD

**Issue by jibben** [Howon/Oscar#20]
We need to enable chained variable assignment for mutable variables (move `vassign` to `expr`)

We also need to make `vdecl` a `stmt` so we can actually declare variables in functions

**Comment by jibben** [comment]
pasta/vassign

**Comment by aethos** [comment]
changes will also need to happen in the ast cause there's no concept of variable assignment

**Comment by vlad-scherbich** [comment]
^^ yea, I made a ticket for that here:

https://github.com/Howon/Oscar/issues/44
