### ISSUE TITLE
complex types

### ISSUE THREAD

**Issue by jibben** [Howon/Oscar#36]
Currently you can only define empty complex types. We need the following to be valid:
`list<int> intList = [1, 2, 3];`
`set<int> tSet = [1, 2, 3]`
`map<int, string> tMap = [0 -> “hi”]`
`tup<int, int> t = (1, 4)`

**Comment by jibben** [comment]
also on pasta/vassign

**Comment by jibben** [comment]
We still need this in AST

**Comment by vlad-scherbich** [comment]
can be closed?
