### ISSUE TITLE
Actor Actions

### ISSUE THREAD

**Issue by aethos** [Howon/Oscar#66]
a lot of stuff apparently

**Comment by vlad-scherbich** [comment]
Namely: 
- ACT_SENDER 
- ACT_DIE 
- ACT_SPAWN 
- ACT_RECEIVE 
- ACT_SEND 
- ACT_BROADCAST

**Comment by jibben** [comment]
ACT_DIE, ACT_SEND, ACT_BROADCAST, ACT_RECEIVE all implemented
